### ISSUE TITLE
Android Azure Storage package

### ISSUE THREAD

**Issue by saio23** [Azure/azure-sdk-for-android#233] opened 2020-04-29 08:12 UTC
Hello, is there going to be any updates on the Azure Storage SDK for Android? I have issues due to minify and Proguard can't build signed APK!

**Comment by bsiegel** [comment] 2020-04-29 21:08
Hi there, thanks for the question. The Azure SDK for Android is expected to replace / succeed the existing [Azure Storage SDK](https://github.com/Azure/azure-storage-android), and it will exist as a single SDK with libraries to access a variety of Azure services rather than just Azure Storage.

We're currently working on a new version of the Android Storage (blobs) library that we expect to have in preview shortly. We will target additional Azure services (including other parts of Storage like queues and tables) in later releases.

Would you mind sharing a little bit about what you're using the Azure Storage SDK for?

**Comment by saio23** [comment] 2020-04-29 21:15
I am trying to use it as a storage for multiple users on an android project for Thesis project. Also I would like to know if there is some way to fix the Minify issues when Generating Signed APK without disabling the minify. Due to the use of androidx libraries the jettifier throws an error on building the apk .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bsiegel** [comment] 2020-04-29 21:18
To clarify, is this the library you are currently attempting to use (and getting errors during minification): https://github.com/Azure/azure-storage-android ?

**Comment by saio23** [comment] 2020-04-29 21:22
Yes, you can find my question here in the package as well, https://github.com/Azure/azure-storage-android/issues/79

Thank you in advance!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bsiegel** [comment] 2020-05-07 18:27
Closing since this is essentially a duplicate of Azure/azure-storage-android#79

**Closed by bsiegel** 2020-05-07 18:27 UTC
Labels: question
